# build.zig.zon-sha256: 1600728e7ae642776c249b3ebadd2edd37765c84f7fd1efcdd8a2d6531da1f91
# generated by zon2nix (https://github.com/nix-community/zon2nix)

{
  linkFarm,
  fetchzip,
  fetchgit,
}:

linkFarm "zig-packages" [
  {
    name = "toml-0.3.0-bV14BRmKAQAWR0FT0KUKFwVJTImaFhWjSe6HfSMtNZOH";
    path = fetchgit {
      url = "https://github.com/sam701/zig-toml";
      rev = "8685923e32e8b8a795eb2715684236975a70faed";
      hash = "sha256-MU+zI9Utu7VaLy9hmyhRZXstfAPUjMSblE8SWLmrK6o=";
    };
  }
  {
    name = "wayland-0.7.0-dev-lQa1kl38AQC-kQolS5D4jV1GJ2rH2jv1VWHr14YLVnyn";
    path = fetchgit {
      url = "https://codeberg.org/ifreund/zig-wayland.git";
      rev = "23839e41161de025d71ce082561ecba1c5331281";
      hash = "sha256-6iehxkESzs7BvKnKlq0XqAYzO2lnl4tdiksaKfuKDhA=";
    };
  }
  {
    name = "xkbcommon-0.5.0-dev-VDqIe0y2AgA1RzA2ICMdGhaAgSXdhtRTbYybQQu7WfOa";
    path = fetchgit {
      url = "https://codeberg.org/ifreund/zig-xkbcommon.git";
      rev = "6c2f41e269adde0d2cd58d20c02c4f8803d83eb1";
      hash = "sha256-vreObBYsAsb33qKdTpQGFqPbweidMw+L1MRWxqwq07E=";
    };
  }
]
