# build.zig.zon-sha256: 02e9921b99b59003c04dea62f591e849af103904e2d86d78dac3372e72bb4554
# generated by zon2nix (https://github.com/nix-community/zon2nix)

{
  linkFarm,
  fetchzip,
  fetchgit,
}:

linkFarm "zig-packages" [
  {
    name = "N-V-__8AAANWAQBoiCxdwbAmaA0PDpYKI0zfFJ1Woy67Tjh2";
    path = fetchgit {
      url = "https://github.com/win-iconv/win-iconv";
      rev = "82f00fbc1b1156530a0bbd003b93b3942743ed27";
      hash = "sha256-51kfw03/cSZzKLupRBjCElfuYi8Bayn2rnQwGH7zyNc=";
    };
  }
  {
    name = "N-V-__8AAB0eQwD-0MdOEBmz7intriBReIsIDNlukNVoNu6o";
    path = fetchzip {
      url = "https://codeload.github.com/madler/zlib/tar.gz/refs/tags/v1.3.1";
      hash = "sha256-TkPLWSN5QcPlL9D0kc/yhH0/puE9bFND24aj5NVDKYs=";
    };
  }
  {
    name = "N-V-__8AAFDiVQA3Q01T64sEaf0mSRyePtaGEqV9gZ37pSti";
    path = fetchzip {
      url = "https://release-assets.githubusercontent.com/github-production-release-asset/321154/a7ac1470-95d7-4036-9735-36099626d83e?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-10-05T21%3A30%3A16Z&rscd=attachment%3B+filename%3Dlibffi-3.5.2.tar.gz&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-10-05T20%3A30%3A03Z&ske=2026-10-05T21%3A30%3A16Z&sks=b&skv=2018-11-09&sig=3NeudFanuGswHPg6%2FE1E%2FGYwSWdBTTmOp4TXYBCcjqk%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc5MTIzMzQ0MSwibmJmIjoxNzkxMjMzMTQxLCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.HSB7my0See8HBf87XhG5kbGjv63zV-pWsk1ID-0Mxa0&response-content-disposition=attachment%3B%20filename%3Dlibffi-3.5.2.tar.gz&response-content-type=application%2Foctet-stream";
      hash = "sha256-FJnD6zD6Jd9Tnxkca+mNzY+zRl7YLzJ5dRhny0l54NY=";
    };
  }
  {
    name = "N-V-__8AAFwJUgGJcIFZ3fj0Q9U_KtvhHdZXlLz1FcAuIcmX";
    path = fetchzip {
      url = "https://ftp.gnu.org/pub/gnu/libiconv/libiconv-1.18.tar.gz";
      hash = "sha256-BS84zQYbV0J+E5XEulbj0Th6YoO9079ype/x2IEF21g=";
    };
  }
  {
    name = "N-V-__8AAGoeGQBEn6KguTJUXrCE0tIRrrXfQX7hYHoKCJwZ";
    path = fetchgit {
      url = "https://gitlab.freedesktop.org/wayland/wayland.git";
      rev = "736d12ac67c20c60dc406dc49bb06be878501f86";
      hash = "sha256-5iG0HaPXJCEo027TuyXlJQNGluTaAPlvwQDFbiYOEJQ=";
    };
  }
  {
    name = "N-V-__8AAJHtBwDe4gR5ofaikfFsHj0vPE-uTQSAkqY2uRv_";
    path = fetchgit {
      url = "https://github.com/jiixyj/epoll-shim";
      rev = "18159584bb3d17e601b9315a7398ace018251bdc";
      hash = "sha256-9rlhRGFT8LD98fhHbcEhj3mAIyqeQGcxQdyP7u55lck=";
    };
  }
  {
    name = "N-V-__8AALGdawC4U4VZt8pBwXK8gBVv2OTdm2naBwU9xHcb";
    path = fetchgit {
      url = "https://github.com/xkbcommon/libxkbcommon";
      rev = "6f76d19db72b5d450e927b41e1e96cbe3252aba8";
      hash = "sha256-wUsxsM0xXTg7nbvFMXrrnHherOepj0YI77eferjRgJA=";
    };
  }
  {
    name = "N-V-__8AAMX2GwiF4I3vxSUHX70z0UP4G2EwLiT2Q9eNGkwN";
    path = fetchgit {
      url = "https://github.com/libexpat/libexpat";
      rev = "f9a3eeb3e09fbea04b1c451ffc422ab2f1e45744";
      hash = "sha256-fAJgHW3KIe5qtQ0ymRiyB8WBt05bMz8b3+JBibCpzQw=";
    };
  }
  {
    name = "N-V-__8AAPCbSwEcttmGC8VZFtoJxaP06X_upd7O13NMUkIf";
    path = fetchzip {
      url = "https://download.gnome.org/sources/libxml2/2.15/libxml2-2.15.1.tar.xz";
      hash = "sha256-N5eIW5K2UC3nf1cIUIIrbAXmCR86fMEh8ZMpC7Ndbzk=";
    };
  }
  {
    name = "aro-0.0.0-JSD1Qi7QNgDnfcrdEJf82v3o6MhZySjYVrtdfEf3E4Se";
    path = fetchgit {
      url = "https://github.com/Vexu/arocc";
      rev = "5f5a050569a95ecc40a426f0c3666ae7ef987ede";
      hash = "sha256-f8Z0SXWx5Uia2TCMB5SUpcO8+xUnaWk32Oknva7xcxw=";
    };
  }
  {
    name = "libexpat-2.7.1-3-y_akI_s7AABtuMADtwTTJGOxx8iY5ZC9T8EON6cjvbNw";
    path = fetchgit {
      url = "https://github.com/allyourcodebase/libexpat";
      rev = "662b7d1cb5f347598d4619d125be317cc2c52b62";
      hash = "sha256-vMLEFTg/usFKqiHw4/rdMSIHtwQSCXdlrydTD/bZ9tQ=";
    };
  }
  {
    name = "libffi-3.5.2-QhHaJ2w4AACSdZtDZIkZWHkCpsK_GLC8DIQS8UnD24I4";
    path = fetchgit {
      url = "https://github.com/allyourcodebase/libffi";
      rev = "29f3c29dd59402dd2112db8252beb57c3966df2d";
      hash = "sha256-M/721is2UPNWQ+78mLmXN/FFfDkyeEZ6jZuAFdYSeUQ=";
    };
  }
  {
    name = "libiconv-1.18.0-p9sJwWnqAAAAD_T5JHJ8v9OrgUtLGT6ov322zOnkUkv5";
    path = fetchgit {
      url = "https://github.com/allyourcodebase/libiconv";
      rev = "d86666233f4e0045b586060260e8a6093f5cdd8d";
      hash = "sha256-sJYOLlNfE6QMSawnoP+TmDOAozbwPWVxAu1+ZVKh4Ig=";
    };
  }
  {
    name = "libxkbcommon-1.13.1-93LaF2x7AgDgSrr8xjRYrYGhtGhJKcZMuID3M95APvl1";
    path = fetchzip {
      url = "https://codeload.github.com/allyourcodebase/libxkbcommon/tar.gz/refs/tags/1.13.1";
      hash = "sha256-o6Rj5wcrqCF8zUpZ6FFCXlTSoMepxoJkGhwu+LMvGK4=";
    };
  }
  {
    name = "libxml2-2.15.1-2-qHdjhmNMAAAiZOWqVridicq2oMf5NHv0n9W41bz9FtMM";
    path = fetchgit {
      url = "https://github.com/allyourcodebase/libxml2";
      rev = "2528fad1bf17a0a70999930cfd9280554f547787";
      hash = "sha256-/slP572iNUkZhZanvDbUasDrO6NxL6sy9xN06xPbIWk=";
    };
  }
  {
    name = "pixman-0.3.0-LClMnz2VAAAs7QSCGwLimV5VUYx0JFnX5xWU6HwtMuDX";
    path = fetchzip {
      url = "https://codeberg.org/ifreund/zig-pixman/archive/v0.3.0.tar.gz";
      hash = "sha256-8tA4auo5FEI4IPnomV6bkpQHUe302tQtorFQZ1l14NU=";
    };
  }
  {
    name = "river-0.4.8-_G6NjkobDACHHnmgSodvwRd6DZim44z8hg8TOcl4VNBS";
    path = fetchzip {
      url = "https://codeberg.org/river/river/archive/v0.4.8.tar.gz";
      hash = "sha256-vqOGyd0sddjYZ47xPMFmfzDIg8mHfIBzAJQ2CcsMQ3Y=";
    };
  }
  {
    name = "translate_c-0.0.0-Q_BUWlX1BgCD1wo6uo97prlp9VJ4gxAjwN_vZ7nsSjGN";
    path = fetchgit {
      url = "https://codeberg.org/ziglang/translate-c/";
      rev = "57c559cf581b1fcad90494eda219f98abeb155ce";
      hash = "sha256-7OlW2f5tRc1UZySDcEQERsLGChSxIcJAiVWdvuFUvvY=";
    };
  }
  {
    name = "tributary-0.4.1-tqCfWzbUAACWcbClrEM-xQIfPNogwri6nGNyWrt123vK";
    path = fetchzip {
      url = "https://codeberg.org/Sivecano/libtributary/archive/0.5.0.tar.gz";
      hash = "sha256-nyJLxQdiQ54gEf31M8tnE8ZGBYbl8tN9GzXsfRrHWIE=";
    };
  }
  {
    name = "wayland-0.6.0-lQa1kqz8AQADQmdNJsNhLoNHcnEGEUjrOaPV-dtEnEmX";
    path = fetchzip {
      url = "https://codeberg.org/ifreund/zig-wayland/archive/v0.6.0.tar.gz";
      hash = "sha256-3m/ITNhZUJ/5uD/Tqm+0uZSktGoYgWF5oldOqOCUkIE=";
    };
  }
  {
    name = "wayland-1.24.0-4-dxEBaw99AACwkS6fa_gXROD4jKQpqkbHR6ZmpjTtUrnD";
    path = fetchzip {
      url = "https://codeload.github.com/allyourcodebase/wayland/tar.gz/a1a2e0870846b804aa19f777ac94705a99e3fb46";
      hash = "sha256-gdjKSJGHxz2vYcMLpkLFzT43JOBuFVH7V8LGA6DUXxI=";
    };
  }
  {
    name = "win_iconv-0.0.10--19NP7MRAAAnmImNeW9llGV-UPmCHV-4MN_FVzNhb-P0";
    path = fetchgit {
      url = "https://github.com/allyourcodebase/win-iconv";
      rev = "341e958b33f1cd1142f00a561510d83e6556f1fd";
      hash = "sha256-dkmEW5TOjX5PwqzOw4Rz4p5NKvBfyia6GObaMI1/A0M=";
    };
  }
  {
    name = "wlroots-0.20.1-jmOlcqNVBAB3uB5oqBTzpRlwu-FmMyyZMVAWCe5kmcSt";
    path = fetchzip {
      url = "https://codeberg.org/ifreund/zig-wlroots/archive/v0.20.1.tar.gz";
      hash = "sha256-cfzHJ2ziiCkMyNlIo6I9o/NjaZGrsv22hq41WYwCnpk=";
    };
  }
  {
    name = "xkbcommon-0.3.0-VDqIe3K9AQB2fG5ZeRcMC9i7kfrp5m2rWgLrmdNn9azr";
    path = fetchzip {
      url = "https://codeberg.org/ifreund/zig-xkbcommon/archive/v0.3.0.tar.gz";
      hash = "sha256-e5bPEfxl4SQf0cqccLt/py1KOW1+Q1+kWZUEXBbh9oQ=";
    };
  }
  {
    name = "xkbcommon-0.4.0-VDqIe0i2AgDRsok2GpMFYJ8SVhQS10_PI2M_CnHXsJJZ";
    path = fetchzip {
      url = "https://codeberg.org/ifreund/zig-xkbcommon/archive/v0.4.0.tar.gz";
      hash = "sha256-zQkmP/cuhAtjOLqYS5D15khKzpqyhbyZ0TD6/8jOkqE=";
    };
  }
  {
    name = "zlib-1.3.1-1-ZZQ7ldENAAA7qJjUXP6E6xnRuV-jDL9dyoJFc_eb3zQ6";
    path = fetchgit {
      url = "https://github.com/allyourcodebase/zlib";
      rev = "c5115f4b69ef660f72a835c6638f80508ef284c7";
      hash = "sha256-s6i7skB5UM5Ix3gsFElUYiyYRs1KCFgcSuGv1rftjYU=";
    };
  }
]
