# build.zig.zon-sha256: 7775a7eb7470294c199459d84fe199b519f26e8e6d72dca38b245a1e28d0b2be
# generated by zon2nix (https://github.com/nix-community/zon2nix)

{
  linkFarm,
  fetchzip,
  fetchgit,
}:

linkFarm "zig-packages" [
  {
    name = "args-0.0.0-CiLiqojRAACGzDRO7A9dw7kWSchNk29caJZkXuMCb0Cn";
    path = fetchgit {
      url = "https://github.com/ikskuh/zig-args";
      rev = "8ae26b44a884ff20dca98ee84c098e8f8e94902f";
      hash = "sha256-LfUIqbHNS6DPvLV68Jxsz7OKJ9+y3ZOuvlja9whe9Wo=";
    };
  }
  {
    name = "fcft-3.0.0-zcx6CxQfAADhnwm8SjyCkQF-VFHGiVarigc2de3ciInC";
    path = fetchzip {
      url = "https://git.sr.ht/~novakane/zig-fcft/archive/4bf5be61c869d08d5bcb0306049c63a9cb0795a7.tar.gz";
      hash = "sha256-iP38R29g9sMbgqVkg7vXSymON6mjxYlVahh7nJ08AVA=";
    };
  }
  {
    name = "kdl-0.0.0-8rilEKdHAQC_NOLDNu3Ts6kJT8uqqJvrPduFScEjSm_g";
    path = fetchzip {
      url = "https://codeberg.org/bwbuhse/zig-kdl/archive/13d9d247324f79b854187d6becc47fffdf7fea3b.tar.gz";
      hash = "sha256-GLGWy1zNhc0sJABD242KpUAOleeJJcb//5d0Lq8bvN4=";
    };
  }
  {
    name = "known_folders-0.0.0-Fy-PJv3LAAABBRVoZWVrKZdyLoUfl5VRY5fqRRRdnF5L";
    path = fetchzip {
      url = "https://github.com/ziglibs/known-folders/archive/83d39161eac2ed6f37ad3cb4d9dd518696ce90bb.tar.gz";
      hash = "sha256-faXaYD+0oe6M9iB4m46O6djWxXuuluNJeJdpIXNj8DM=";
    };
  }
  {
    name = "pixman-0.3.0-LClMnz2VAAAs7QSCGwLimV5VUYx0JFnX5xWU6HwtMuDX";
    path = fetchzip {
      url = "https://codeberg.org/ifreund/zig-pixman/archive/v0.3.0.tar.gz";
      hash = "sha256-8tA4auo5FEI4IPnomV6bkpQHUe302tQtorFQZ1l14NU=";
    };
  }
  {
    name = "wayland-0.5.0-dev-lQa1kv_ZAQCZfnVZMocokZ78QJbH6NaM5RUC9ODQPhx5";
    path = fetchzip {
      url = "https://codeberg.org/ifreund/zig-wayland/archive/e57368ecbda85d564362779b253b744260a4b053.tar.gz";
      hash = "sha256-DwBIY4v6jZ7YhCRFvYujRmpIVtO9hSSpIbESpl6hbIU=";
    };
  }
  {
    name = "xkbcommon-0.4.0-dev-VDqIe0y2AgCNeWLthDZ3MUcUYzhyKXjK85ISm_zxk9Nk";
    path = fetchzip {
      url = "https://codeberg.org/ifreund/zig-xkbcommon/archive/6786ca619bb442c3f523b5bb894e6a1e48d7e897.tar.gz";
      hash = "sha256-jawZMAcfjHKaTyGbyeMtsQv1q2rizrIXpGELJB/fFXc=";
    };
  }
  {
    name = "zeit-0.6.0-5I6bk36tAgATpSl9wjFmRPMqYN2Mn0JQHgIcRNcqDpJA";
    path = fetchzip {
      url = "https://github.com/rockorager/zeit/archive/7ac64d72dbfb1a4ad549102e7d4e232a687d32d8.tar.gz";
      hash = "sha256-CDYwSqx0xA3Xx7/eDCtP0lHbheIScPwnffV2nxzJ/mU=";
    };
  }
  {
    name = "zigimg-0.1.0-8_eo2kSGFwADIkeZYTgfnLOV-khh6ZRoGmK6F2-s_QbY";
    path = fetchzip {
      url = "https://github.com/zigimg/zigimg/archive/fb74dfb7c6d83f2bd01a229826669451525a4ba8.tar.gz";
      hash = "sha256-za+zjP3fzbUUZYsCqo742VUTysDzfdEcT4MXNCfqceU=";
    };
  }
]
