# generated by zon2nix (https://github.com/nix-community/zon2nix)

{
  linkFarm,
  fetchzip,
  fetchgit,
}:

linkFarm "zig-packages" [
  {
    name = "1220997e7559328728919efc4096c7e8d68ce51502f4e0d03e1c79a313992e22532a";
    path = fetchzip {
      url = "https://codeberg.org/ifreund/zig-wayland/archive/main.tar.gz";
      hash = "sha256-DwBIY4v6jZ7YhCRFvYujRmpIVtO9hSSpIbESpl6hbIU=";
    };
  }
]
