# build.zig.zon-sha256: 2a12973f0da7507cf449a54a0bd8e1dc451627a7c06df3d86ddaee07c4ca0b52
# generated by zon2nix (https://github.com/nix-community/zon2nix)

{
  linkFarm,
  fetchzip,
  fetchgit,
}:

linkFarm "zig-packages" [
  {
    name = "mr_tween-0.1.0-WbH78YcBAQD3RF4QfCYFF6EJCYzAzdIU4BHCj0pFI5yq";
    path = fetchgit {
      url = "https://codeberg.org/Games-by-Mason/mr_tween.git";
      rev = "c20266b0629a828a2b166856b1b543cde7c9a898";
      hash = "sha256-+f3klYdTikb7qoggebyOET+xHH9IuZt78MQTfpJOZjM=";
    };
  }
  {
    name = "wayland-0.5.0-lQa1knz8AQCh08NA8BeQrwJB9U3CfqcVAdHZYGRKIGuu";
    path = fetchgit {
      url = "https://codeberg.org/ifreund/zig-wayland";
      rev = "0b7fc007d6f402496e3ad2d6a7cc9118a2080aa9";
      hash = "sha256-mhqOtC26iACIvQUq74AbLSXSPsnWMi3AvDV7G2uElpo=";
    };
  }
]
