# build.zig.zon-sha256: 9354b34ccfb376ed7589ff962df90fbd28b3496ee3c68ed8dd4e00cfaf63a19e
# generated by zon2nix (https://github.com/nix-community/zon2nix)

{
  linkFarm,
  fetchzip,
  fetchgit,
}:

linkFarm "zig-packages" [
  {
    name = "mr_tween-0.1.0-WbH78YcBAQD3RF4QfCYFF6EJCYzAzdIU4BHCj0pFI5yq";
    path = fetchgit {
      url = "https://codeberg.org/Games-by-Mason/mr_tween.git";
      rev = "c20266b0629a828a2b166856b1b543cde7c9a898";
      hash = "sha256-+f3klYdTikb7qoggebyOET+xHH9IuZt78MQTfpJOZjM=";
    };
  }
  {
    name = "tributary-0.1.1-tqCfW9GBAAC3bRMfGE8jA4iqZuG8UdLjsfMfC-GXip_k";
    path = fetchzip {
      url = "https://codeberg.org/Sivecano/libtributary/archive/0.1.1.tar.gz";
      hash = "sha256-1tlzWKp7SiHeIjgNJbs65l26wdMWEWM0wIIMSPx/LnM=";
    };
  }
  {
    name = "wayland-0.6.0-lQa1kqz8AQADQmdNJsNhLoNHcnEGEUjrOaPV-dtEnEmX";
    path = fetchzip {
      url = "https://codeberg.org/ifreund/zig-wayland/archive/v0.6.0.tar.gz";
      hash = "sha256-3m/ITNhZUJ/5uD/Tqm+0uZSktGoYgWF5oldOqOCUkIE=";
    };
  }
]
