# build.zig.zon-sha256: ae413fc7427daf19651d9fd415ebc12084111dbc16e0f5da64a843bef7722bad
# generated by zon2nix (https://github.com/nix-community/zon2nix)

{
  linkFarm,
  fetchzip,
  fetchgit,
}:

linkFarm "zig-packages" [
  {
    name = "mr_tween-0.1.0-WbH78YcBAQD3RF4QfCYFF6EJCYzAzdIU4BHCj0pFI5yq";
    path = fetchzip {
      url = "https://codeberg.org/Games-by-Mason/mr_tween/archive/v0.1.0.tar.gz";
      hash = "sha256-+f3klYdTikb7qoggebyOET+xHH9IuZt78MQTfpJOZjM=";
    };
  }
  {
    name = "tributary-0.4.1-tqCfWxDJAACeaPXfsUARn7tSPyFkoIlrfuvPNy1xD7e7";
    path = fetchgit {
      url = "https://codeberg.org/Sivecano/libtributary";
      rev = "3d83493bc4214772f15b73553b1474c3641c022d";
      hash = "sha256-UlXQbZLccYl8lxEc4AvcP5H7OcrEvZmPYW0dQd2bWII=";
    };
  }
  {
    name = "wayland-0.6.0-lQa1kqz8AQADQmdNJsNhLoNHcnEGEUjrOaPV-dtEnEmX";
    path = fetchzip {
      url = "https://codeberg.org/ifreund/zig-wayland/archive/v0.6.0.tar.gz";
      hash = "sha256-3m/ITNhZUJ/5uD/Tqm+0uZSktGoYgWF5oldOqOCUkIE=";
    };
  }
]
